trigger:
- main

pool:
  name: Default
  demands:
  - Agent.Name -equals MANUSREE

stages:

- stage: Terraform_Plan
  displayName: Terraform Init and Plan

  jobs:
  - job: InitAndValidate
    displayName: Terraform Init and Plan

    steps:

    - checkout: self

    - script: |
        terraform version
      displayName: "Check Terraform Version"

    - script: |
        terraform init
      displayName: "Terraform Init"

    - script: |
        terraform validate
      displayName: "Terraform Validate"

    - script: |
        terraform plan -var="subscription_id=$(subscription_id)"
      displayName: "Terraform Plan"
  
  - job: TerraformApply
    displayName: "Job 2 - Terraform Apply"

    dependsOn: InitAndValidate

    condition: succeeded()

    pool:
      name: Default
      demands:
      - Agent.Name -equals MANUSREE

    steps:

    - checkout: self

    - script: |
        terraform version
      displayName: "Terraform Version"

    - script: |
        terraform init
      displayName: "Terraform Init"

    - script: |
        terraform apply -auto-approve -var="subscription_id=$(subscription_id)"
      displayName: "Terraform Apply"